FROM ubuntu:18.04
LABEL maintainer="Gary R. Engler, Ph.D. (gary.r.engler@gmail.com)"

RUN apt-get update && \
	apt-get install -y \
		python3-dev \
	    python3-pip

RUN mkdir /app

COPY service_01/requirements.txt /app
COPY _utilities/requirements.txt /app/utility_requirements.txt

WORKDIR /app

RUN pip3 install -r requirements.txt
RUN pip3 install -r utility_requirements.txt

COPY service_01/. /app
COPY _utilities/. /app/utilities

CMD ["uwsgi","--ini","/app/homework_template.ini"]

